# Testing Hyperdrive-daemon

So I've installed the hyperdrive-daemon on a _Raspberry Pi 3 Model B+_ and was able to get it [running](hyper://86fcdeb5ebb4a720f4e5b66fbab67a8051ddf09659cd2622cdeb0de8c4d41267/links/bookmarks/beakerbrowser/hyperdrive-daemon-issue-49.goto). 

So far it's working pretty well. Not perfect however as I'm getting some "file descriptor" errors when opening certain files. Probably _mounts_ related. Investigating further.

Initially loading of drives seems to work fine, but then consecutive updates do not seem to show up. At least not immediately.

Wondering if this is an issue or a feature? Could it be related to running both systems on the same network? Worked before between my work and private machines, so why would this be any different?

Looking up how to "update" a drive.
